### ISSUE TITLE
Refresh buttons disappeared in IJ 15

### ISSUE THREAD

**Issue by destin** [destin/maven-test-support-plugin#12]
Refresh and auto-refresh buttons are no longer visible in IJ 15

**Comment by brcolow** [comment]
I can confirm this issue. Really inhibits usability of this really awesome plugin.

**Comment by destin** [comment]
Thanks for feedback. I was not aware that this is that useful. I'll the fix it as soon as I find enough time. Hopefully beginning of next week the fix will be ready.

**Comment by brcolow** [comment]
Thank you!

**Comment by destin** [comment]
I wish it took less time. Nevertheless it is done. Unfortunately IntelliJ API changed and the buttons are now harder to find. I have found no easy solution for this so I release the plugin now and try to find way to improve that later.
