### ISSUE TITLE
Tab Refresh

### ISSUE THREAD

**Issue by Narimm** [destin/maven-test-support-plugin#4]
When you right click and select to view test results the interface tells you "Test in progress".  In my case all 618 tests past - however I imagine because no failed test appeared I couldnt get the interface to update after reporting the result (ie Refresh) closing it and re right clicking immediately resolved the problem, 

To clarify even after the test had completed the interface reported "testing in progress"

Is it possible for the program to refresh and report during a test run, so its almost an interactive result.

**Comment by destin** [comment]
I fixed handling of some edge cases so that "Test in progress" is no longer shown. However you still need to update results manually. It will take me some time to introduce automatic update but still I plan to do this.

**Comment by destin** [comment]
Finally auto-refresh added. Now every time results change on disk the test window will be updated with newest results.

For now the feature is disabled by default as it is still experimental. You enable Auto-refresh for each tab separately.
