### ISSUE TITLE
Should be possible to see all tests in all modules of a multi-module project

### ISSUE THREAD

**Issue by tpischke** [destin/maven-test-support-plugin#5]
We have a large project with many submodules.  Checking the tests for each submodule individually is too much manual work.  Could a feature be added, allowing all tests in all submodules to be visible at once?

**Comment by destin** [comment]
Hi tpischke. Thanks for improvement proposal. I don't see any technical obstacles to display all tests from submodules. I'll add this feature when I find few minutes of spare time, hopefully this month.

**Comment by tpischke** [comment]
Great,  We found a workaround.  In the maven view in Intellij, you can multi select modules and open the tests.  Then they open in many tabs (50+ for our project!).  This is OK, but would be better to have a solution that can display all tests in a tree in a single tab.

**Comment by destin** [comment]
Finally I managed to finish "Auto refresh" feature. Now I can start with showing all tests in all submodules. Should be easier than "Auto refresh". Hopefully I'll get this running even this week.

**Comment by destin** [comment]
Implemented in version 0.0.15.
